#!/bin/sh
BUCKET=reinvent2013-blog-demo-cryptofork

aws s3 sync . s3://$BUCKET \
  --exclude '*' --include '*.js' --include '*.html' --include '*.css' --include '*.png' \
  --region eu-west-1 --acl public-read
